version: '2'

services:
  mysql:
    container_name: some_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'prestashop'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - "./mysql/:/var/lib/mysql"
    ports:
      - 3306
    networks:
      - backend

  presta:
    container_name: some_prestashop
    image: prestashop/prestashop
    restart: always
    environment:
      DB_SERVER: 'some_mysql'
      PS_LANGUAGE: 'pl'
      PS_COUNTRY: 'PL'
    ports:
      - 80
      - 443
    volumes:
      - "./php.ini:/usr/local/etc/php/php.ini"
    networks:
      - frontend
      - backend


  nginx:
    container_name: some_nginx
    image: nginx
    volumes:
      - "./nginx/conf.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/cert/cert.pem:/etc/nginx/cert/cert.pem"
      - "./nginx/cert/cert.key:/etc/nginx/cert/cert.key"
    ports:
      - 8080:8080
      - 443:443
    links:
      - presta
    networks:
      - frontend

networks:
  frontend:
  backend:


