version: '2'

services:
  mysql:
    container_name: some_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'prestashop'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - "./mysql/:/var/lib/mysql"
        #ports:
        # - 3306
    networks:
      - backend

  presta:
    container_name: some_prestashop
    image: prestashop/prestashop
    restart: always
    environment:
      DB_SERVER: 'some_mysql'
      PS_LANGUAGE: 'pl'
      PS_COUNTRY: 'PL'
      PS_ENABLE_SSL: 1
        #ports:
        #- 8000:80
        #- 3000:443
    volumes:
      - "./.htaccess:/var/www/html/.htaccess"
    networks:
      - frontend
      - backend


  nginx:
    container_name: some_nginx
    image: nginx
    volumes:
      - "./nginx/conf.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/cert/selfsigned.crt:/etc/nginx/cert/selfsigned.crt"
      - "./nginx/cert/selfsigned.key:/etc/nginx/cert/selfsigned.key"
    ports:
      - 80:80
      - 443:443
    links:
      - presta
    networks:
      - frontend

networks:
  frontend:
  backend:


