version: '3'

services:
  #mysql:
  #  container_name: some_mysql
  #  image: mysql:5.7
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: 'prestashop'
  #    MYSQL_ROOT_PASSWORD: 'admin'
  #  volumes:
  #    - "./mysql/:/var/lib/mysql"
  #  networks:
  #    - backend

  presta:
    container_name: prestashop
    build:
      context: ./prestashop/
        #  volumes:
        # - "/mnt/block-storage/students/17290/img/:/var/www/html/img_import/"
    environment:
      PS_LANGUAGE: 'pl'
      PS_COUNTRY: 'PL'
      PS_ENABLE_SSL: 1
    networks:
      - frontend
      - backend
    deploy:
      restart_policy:
        max_attempts: 3
        window: 120s
     
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - presta
    networks:
      - frontend
    deploy:
      restart_policy:
        max_attempts: 3
        window: 120s
        
networks:
  frontend:
  backend:
