FROM prestashop/prestashop
COPY .htaccess /var/www/html/.htaccess
# do zakomentowania - umieścić img w /mnt/block-storage/students/17290/
COPY img /var/www/html/img_import
# COPY config /var/www/html/app/config

