<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE6Wi071\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE6Wi071/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerE6Wi071.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerE6Wi071\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerE6Wi071\appAppKernelProdContainer([
    'container.build_hash' => 'E6Wi071',
    'container.build_id' => '00ebaaf4',
    'container.build_time' => 1671353635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE6Wi071');
